[package]
name = "filmrolls"
version = "0.1.0"
authors = ["Simon Sigurdhsson <Sigurdhsson@gmail.com>"]
description = "Tag TIFF files with EXIF data extracted from XML"
repository = "https://github.com/urdh/filmrolls-rs/"
keywords = ["exif", "tool", "photography"]
categories = ["command-line-utilities", "multimedia::images"]
license = "ISC"

edition = "2021"
rust-version = "1.75"

[dependencies]
