coverage:
  precision: 2
  range: 75...100
  status:
    project:
      default:
        threshold: 10%
        paths: ["src"]
    patch:
      default:
        threshold: 75%
        only_pulls: true
        paths: ["src"]
    changes:
      default:
        informational: true
        paths: ["src"]

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  behavior: default
  require_changes: true

github_checks:
    annotations: true
